name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-24"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODE4NDBhNzctY2Q5OS00MTA4LWE5ODYtMmExZWFkYzViZmRlIiwidGVuYW50X2lkIjoiNjdlNTJkZDc2ZjY3MjkyYmUyNTlmODUxNDliZWVkZGE2MjU4MTI4MTk5Y2QyMDQyMDI1ZDUzOGI4YjVhNzA4NyIsImludGVybmFsX3NlY3JldCI6IjYxNTMwZDgyLTRiYjEtNDI3ZC1hNDQ3LTA4YmFhYjg4NjgwZCJ9.MXIqQqCWZZKxH_GkYP3r4_Yg2ryb8uUyyUjUClWQtTM"
